-- TestPlan A3 -- one-time server setup, run by the owner, not by the test.
--
-- Creates a database and a user scoped to it and nothing else. The test drops and recreates its
-- own tables on every run, so it needs real DDL rights -- but only inside astoria_test, which is
-- why this grants on `astoria_test`.* rather than *.*. If the test ever goes wrong, the blast
-- radius is one throwaway database.
--
-- DO NOT EDIT THIS FILE -- it is tracked in git, and a password typed here would be committed.
-- Work on an untracked copy instead; *.local.sql under Examples/Integration is gitignored:
--
--   Copy-Item setup_astoria_test.sql setup_astoria_test.local.sql
--
-- Edit CHANGE_ME in the .local.sql copy, then run it as root. PowerShell has no "<" redirection,
-- so pipe the file in rather than redirecting it:
--
--   Get-Content setup_astoria_test.local.sql | & "C:\Program Files\MariaDB 12.3\bin\mysql.exe" -u root -p
--
-- That prompts for the ROOT password interactively, which is why it has to be run by hand.
--
-- Then tell the test where to look, in the SAME shell you run it from:
--
--   $env:MARIADB_TEST_PASSWORD = "the password you chose"
--
-- The password stays in the untracked copy and the environment. It never reaches a commit.

CREATE DATABASE IF NOT EXISTS astoria_test
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- utf8mb4 deliberately: the test writes non-ASCII text to prove the control's UTF-8 conversion
-- survives a round trip, and utf8mb3 would silently mangle anything outside the BMP.

CREATE USER IF NOT EXISTS 'astoria_test'@'localhost' IDENTIFIED BY 'CHANGE_ME';

GRANT ALL PRIVILEGES ON astoria_test.* TO 'astoria_test'@'localhost';

FLUSH PRIVILEGES;

SELECT 'astoria_test database and user are ready' AS status;
