# TestPlan D1 -- console app lifecycle, driven entirely through the IDE's agent pipe.
# create -> edit -> build -> run -> read output -> close (switch away) -> reopen -> verify.
$ErrorActionPreference = "Stop"

function Send-Pipe([string]$json, [int]$timeoutMs = 180000) {
    $c = New-Object System.IO.Pipes.NamedPipeClientStream('.','AstoriaAgent',[System.IO.Pipes.PipeDirection]::InOut)
    $c.Connect(5000); $c.ReadMode = [System.IO.Pipes.PipeTransmissionMode]::Byte
    $w = New-Object System.IO.StreamWriter($c,(New-Object System.Text.UTF8Encoding($false))); $w.AutoFlush = $true
    $r = New-Object System.IO.StreamReader($c,(New-Object System.Text.UTF8Encoding($false)))
    $w.WriteLine($json); $line = $r.ReadLine(); $c.Dispose(); return $line
}
function J([hashtable]$o) { $o | ConvertTo-Json -Compress -Depth 6 }

$results = @()
function Check([string]$what, [bool]$ok, [string]$detail = "") {
    $script:results += [pscustomobject]@{ Check = $what; Pass = $ok; Detail = $detail }
    "{0}  {1}{2}" -f $(if ($ok) { "PASS" } else { "FAIL" }), $what, $(if ($detail) { "  -- $detail" } else { "" })
}

$name = "D1_ConsoleLifecycle"
$root = "C:\Users\don\Astoria-IDE\Projects\$name"
if (Test-Path $root) { Remove-Item $root -Recurse -Force }

# --- 1. CREATE from the Console Application template ---
$r = Send-Pipe (J @{ id=1; cmd="create_project"; args=@{ name=$name; template="Console Application" } })
Check "create_project succeeds" ($r -match '"ok":true') $r.Substring(0, [Math]::Min(90,$r.Length))
Start-Sleep -Seconds 2

$mainPath = "$root\Main.bas"
Check "template main file exists on disk" (Test-Path $mainPath) $mainPath

# --- 2. EDIT: replace the body with something whose output we can assert on ---
$marker = "D1-MARKER-" + (Get-Random -Minimum 10000 -Maximum 99999)
$src = @"
'' TestPlan D1 -- console lifecycle fixture (generated by the test).
'' Prints a marker and a computed value, so the run step asserts on real output
'' rather than merely on the process exiting 0.
Dim As Integer total = 0
For i As Integer = 1 To 100
    total += i
Next i
Print "$marker"
Print "sum="; total
Sleep 300
"@
$r = Send-Pipe (J @{ id=2; cmd="write_file"; args=@{ path=$mainPath; content=$src } })
Check "write_file (edit) succeeds" ($r -match '"ok":true')

# --- 3. BUILD ---
$r = Send-Pipe (J @{ id=3; cmd="build" })
Check "build succeeds" ($r -match '"exit_code":0')
$exe = "$root\Main.exe"
Check "executable produced" (Test-Path $exe)

# --- 4. RUN and read the output back ---
$r = Send-Pipe (J @{ id=4; cmd="run" })
$out = ""
try { $out = ($r | ConvertFrom-Json).result.output } catch { $out = $r }
Check "run returns the marker"  ($out -match [regex]::Escape($marker)) ("output len " + $out.Length)
Check "run returns computed sum" ($out -match "sum=\s*5050") ($out -replace "\s+"," ").Trim()

# --- 5. CLOSE: switch to a different project, so the original is no longer loaded ---
$other = "C:\Users\don\Astoria-IDE\Examples\Controls\Label\Label.vfp"
$r = Send-Pipe (J @{ id=5; cmd="open_project"; args=@{ path=$other } })
Check "switch away to another project" ($r -match '"ok":true')
Start-Sleep -Seconds 2
$st = Send-Pipe (J @{ id=6; cmd="get_status" })
Check "IDE no longer on the D1 project" (-not ($st -match [regex]::Escape($name)))

# --- 6. REOPEN and verify the edit survived ---
$r = Send-Pipe (J @{ id=7; cmd="open_project"; args=@{ path="$root\$name.vfp" } })
Check "reopen the D1 project" ($r -match '"ok":true')
Start-Sleep -Seconds 2
$r = Send-Pipe (J @{ id=8; cmd="open_in_editor"; args=@{ path=$mainPath } })
Start-Sleep -Seconds 2
$af = Send-Pipe (J @{ id=9; cmd="get_active_file" })
$content = ""
try { $content = ($af | ConvertFrom-Json).result.content } catch { }
Check "edited source survived close/reopen" ($content -match [regex]::Escape($marker))

# --- 7. Rebuild after reopen: proves the reopened project is genuinely usable ---
$r = Send-Pipe (J @{ id=10; cmd="build" })
Check "rebuild after reopen succeeds" ($r -match '"exit_code":0')

""
$passed = ($results | Where-Object { $_.Pass }).Count
$total  = $results.Count
"D1 RESULT: $passed/$total"
if ($passed -ne $total) { $results | Where-Object { -not $_.Pass } | Format-Table -AutoSize | Out-String }
