name: windows

on:
  [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build
      shell: cmd
      run: |
        set NOPAUSE=1
        call Compile.bat
        exit /b %errorlevel%
